# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c8abc18449fa235b897a538c2b0fa87a712f36e6684d079ea829de8cfa0870cb4b146666fd82d98ab426ecbe88c80ad7f41cda954768c2aa122bac6ce5eaf9

test:
  secret_key_base: 856ee11d348206710f99d2089be51ff0c03a80ef4db47f1719b8618cc87432c8412edf54cfe111ad1adf95cf2ddbb967bc56ec0107b671daadca458f7e372022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
